server:
  port: 80

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://54.180.67.94:3306/cu_license
    username: root
    password: cubox2024!
    driver-class-name: org.mariadb.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: cubox-ti@cubox.ai
    password: hkcrwgwfwucmjhhi
  profiles:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

# Log 설정
